#!/bin/bash

###################################################
#				                  #
# ==> Autor: Daniel Diaz                          #
#                                                 #
###################################################

{
echo -e "Let's install YAY. We can proceed? (y/N)?"
read answer
    if [[ $answer = [sSyY] ]]; then
        echo -e "\nInstalling...\n"

        sudo pacman -S --noconfirm --needed git
sleep 1

git clone https://aur.archlinux.org/paru-bin
sleep 0.5
cd paru-bin
sleep 0.5
makepkg -si

else
        sair
    fi
}

sair() {
    echo -e "\nGoing out...\n"
    exit 0
}
